projeto_tg/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<order_item_id>[\w-]+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<order_item_id>[\w-]+)/$', views.cart_remove, name='cart_remove'),
]

projeto_tg/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.contrib.auth import views
from . import views as index_view

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r"^account/", include("allauth.urls")),
    url(r"^accounts/", include("allauth.urls")),
    url(r"^api/v1/", include("projeto_tg.api.urls")),
    url(r"^api/v1/auth/", include("djoser.urls.authtoken")),
    url(r'^social-auth/', include('social_django.urls', namespace="social")),
    # path('accounts/', include('django.contrib.auth.urls')),
    url(r'^$',index_view.index_view,name='home'),
    url(r'^cart/', include(('projeto_tg.cart.urls', 'cart'), namespace='cart')),
    url(r'event_carousel/',index_view.get_events),
    url(r'^event/', include('projeto_tg.evento.urls')),
    url(r'^profile/', include('projeto_tg.people.urls')),
    url(r'^order/', include('projeto_tg.order.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^search/autocomplete_city', index_view.autocomplete_city),
    url(r'^search/autocomplete', index_view.autocomplete)

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.LOCAL_MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

projeto_tg/cart/models.py
from django.shortcuts import render
from django.conf import settings
from decimal import Decimal
from projeto_tg.evento.models import Evento
from django.db import models

# Create your views here.

class Cart(object):

  def __init__(self, request):
        """
        Initialize the cart.
        """
        self.session = request.session
        cart = self.session.get(settings.CART_SESSION_ID)
        if not cart:
            # save an empty cart in the session
            cart = self.session[settings.CART_SESSION_ID] = {}
        self.cart = cart

  def add(self, order_item, quantity=1, update_quantity=False):
    order_item_id = order_item.id_hash
    if order_item_id not in self.cart:
      self.cart[order_item_id] = {
                            'quantity': 0,
                            'price':str(order_item.price)}
    if update_quantity:
      self.cart[order_item_id]['quantity'] = quantity
    else:
      self.cart[order_item_id]['quantity'] += quantity
    self.save()

  def save(self):
    self.session[settings.CART_SESSION_ID] = self.cart
    self.session.modified = True

  def remove(self, order_item):
    order_item_id = order_item.id_hash
    if order_item_id in self.cart:
      del self.cart[order_item_id]
      self.save()
  
  def __iter__(self):
    order_item_ids = self.cart.keys()
    orders = Evento.objects.filter(id_hash__in=order_item_ids)
    for order in orders:
      self.cart[str(order.id_hash)]['order'] = order
    
    for item in self.cart.values():
      item['price'] = Decimal(item['price'])
      item['total_price'] = item['price'] * item['quantity']
      yield item

  def __len__(self):
    return sum(item['quantity'] for item in self.cart.values())

  def get_total_price(self):
        return sum(Decimal(item['price']) * item['quantity'] for item in self.cart.values())

  def clear(self):
      # remove cart from session
      del self.session[settings.CART_SESSION_ID]
      self.session.modified = True

projeto_tg/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddOrderItemForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

projeto_tg/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms.models import model_to_dict
from django.views.decorators.http import require_POST

from projeto_tg.evento.models import Evento
from .models import Cart
from .forms import CartAddOrderItemForm


@require_POST
def cart_add(request, order_item_id):
    cart = Cart(request)
    order_item = get_object_or_404(Evento, id_hash=order_item_id)
    form = CartAddOrderItemForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(order_item=order_item,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, order_item_id):
    cart = Cart(request)
    order_item = get_object_or_404(Evento, id_hash=order_item_id)
    cart.remove(order_item)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddOrderItemForm(
            initial={
                'quantity': item['quantity'],
                'update': True
            })
    return render(request, 'cart/cart_detail.html', {'cart': cart})

projeto_tg/cart/templates/cart/cart_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap4 %}

{% block title %}Carrinho de compras{% endblock %}

{% block middle %}
<div class="container" style="margin-top:100px">
    <h1>Seu carrinho de compras</h1>
    <div class="row">
        <div class="col-sm-12 col-md-10 col-md-offset-1">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>Evento</th>
                    <th>Quantidade</th>
                    <th class="text-center">Preço</th>
                    <th class="text-center">Total</th>
                    <th> </th>
                </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with event=item.order %}
                        <tr>
                            <td class="col-sm-8 col-md-6">
                                <div class="media">
                                    <a class="thumbnail pull-left" href="{% url 'event_detail' event=event.id_hash %}">
                                        <img class="media-object"
                                             src="/uploaded/{{ event.image_file }}"
                                             style="width: 72px; height: 72px;">
                                    </a>
                                    <div class="media-body">
                                        <h4 class="media-heading"><a
                                                href="{% url 'event_detail' event=event.id_hash %}">{{ event.name }}</a></h4>
                                        <span>Status: </span><span class="text-success"><strong>Em estoque</strong></span>
                                    </div>
                                </div>
                            </td>
                            <td class="col-sm-1 col-md-1" style="text-align: center">
                                <form action="{% url "cart:cart_add" event.id_hash %}" method="post">
                                    {% csrf_token %}
                                    {% bootstrap_field item.update_quantity_form.quantity show_label=False %}
                                    {% bootstrap_field item.update_quantity_form.update %}
                                    {% buttons %}
                                        <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored">
                                            Atualizar
                                        </button>
                                    {% endbuttons %}
                                </form>
                            </td>

                            <td class="col-sm-1 col-md-1 text-center"><strong>R${{ item.price }}</strong></td>
                            <td class="col-sm-1 col-md-1 text-center"><strong>R${{ item.total_price }}</strong></td>

                            <td class="col-sm-1 col-md-1">
                                <a href="{% url "cart:cart_remove" event.id_hash %}" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">
                                    <i class="glyphicon glyphicon-remove" aria-hidden="true"></i> Remover
                                </a>
                            </td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr>
                    <td>  </td>
                    <td>  </td>
                    <td>  </td>
                    <td><h3>Total</h3></td>
                    <td class="text-right"><h3><strong>R${{ cart.get_total_price }}</strong></h3></td>
                </tr>
                <tr>
                    <td>  </td>
                    <td>  </td>
                    <td>  </td>
                    <td>
                        <a href="{% url 'home' %}" class="btn btn-success">
                            Continuar Comprando <i class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></i>
                        </a>
                    </td>
                    <td>
                        {% if not user.is_authenticated %}
                            <a href="#" class="btn btn-danger" data-toggle="modal" role="button" data-target="#modal-options">Finalizar Compra 
                                <i class="glyphicon glyphicon-play" aria-hidden="true"></i>
                            </a>
                        {% else %}
                            <button id="checkout_order" class="btn btn-danger">Finalizar Compra 
                                <i class="glyphicon glyphicon-play" aria-hidden="true"></i>
                            </button>
                        {% endif %}
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <script>
    $("#checkout_order").on('click', (e) => {
        $.ajax({
            url: "{% url 'checkout_order' %}",
            method: 'POST',
            beforeSend: (xhr) => {
                xhr.setRequestHeader('X-CSRFTOKEN', "{{ csrf_token }}");
            },
            complete: (data) => {
                console.log(data);
            }
        })
    })
    </script>
</div>
{% endblock %}